### ISSUE TITLE
How to create a new sql

### ISSUE THREAD

**Issue by rezamonangg** [kukymbr/goose-docker#3]
Hi, thank you for this docker image which really helps me right now. But now i'm stuck because i cannot create a new sql file using docker-compose. This is how i run the command

```
migrator:
    image: ghcr.io/kukymbr/goose-docker:3.19.2
    env_file:
      - .env
    volumes:
      - ./pkg/infrastructure/database/migrations:/migrations
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy
    profiles:
      - dev
```

```
GOOSE_COMMAND="create" GOOSE_COMMAND_ARG="seed_user" docker-compose run --rm migrator
```

**Comment by kukymbr** [comment]
Hi, nice to see this repository to be useful. 
You should add the `GOOSE_COMMAND` and the `GOOSE_COMMAND_ARG ` to the `environment` section of the `migrator` service:

```yaml
migrator:
    # ...
    environment:
      - GOOSE_COMMAND=${GOOSE_COMMAND}
      - GOOSE_COMMAND_ARG=${GOOSE_COMMAND_ARG}
```

This format allows to override environment values.

I'll add this information to the readme.
